---
- name: Assert that prerequisites exist
  tags: lux-release
  assert:
    that:
      - lux_pkg is defined
      - lux_rel is defined

- name: Set lux_ver fact (el7)
  tags: lux-release
  set_fact:
    lux_ver: "7-1"
  when: lux_rel == '7'

- name: Set lux_ver fact (el6)
  tags: lux-release
  set_fact:
    lux_ver: "6-3"
  when: lux_rel == '6'

- name: Set lux_ver fact (el5)
  tags: lux-release
  set_fact:
    lux_ver: "0-1"
  when: lux_rel == '5'

- name: Execute mktemp
  tags: lux-release
  command: mktemp -u --suffix .rpm
  register: lux_mktemp

- name: Create temporary package
  tags: lux-release
  get_url:
    url: "https://www.lux.org/{{ lux_pkg }}-{{ lux_ver }}.noarch.rpm"
    dest: "{{ lux_mktemp.stdout }}"
  register: lux_get_url
  when: lux_mktemp|success

- name: Install lux-release
  tags: lux-release
  yum:
    name: "{{ item }}"
    state: present
  register: lux_yum
  with_items: "{{ lux_mktemp.stdout }}"
  when: lux_get_url|success

- name: Configure lux.repo
  tags: lux-release
  template:
    src: lux.repo.j2
    dest: /etc/yum.repos.d/lux.repo
    owner: root
    group: root
    mode: 0644
  when: lux_yum|success

- name: Erase temporary package
  tags: lux-release
  file:
    path: "{{ lux_mktemp.stdout }}"
    state: absent
  when:
    - lux_mktemp|success
    - lux_yum|success
...
