---
- name: Assert that the prerequisites are defined
  tags: lux
  assert:
    that:
      - lux_pkg is defined
      - lux_rel is defined

- name: Setting lux_ver fact (el7)
  tags: lux
  set_fact:
    lux_ver: "7-1"
  when: lux_rel == '7'

- name: Setting lux_ver fact (el6)
  tags: lux
  set_fact:
    lux_ver: "6-3"
  when: lux_rel == '6'

- name: Setting lux_ver fact (el5)
  tags: lux
  set_fact:
    lux_ver: "0-1"
  when: lux_rel == '5'

- name: Generating temporary filename via mktemp
  tags: lux
  command: mktemp -u --suffix .rpm
  register: lux_mktemp

- name: Downloading package to temporary location
  tags: lux
  get_url:
    dest: "{{ lux_mktemp.stdout }}"
    url: "http://repo.iotti.biz/CentOS/{{ lux_rel }}/noarch/{{ lux_pkg }}-{{ lux_ver }}.noarch.rpm"
  register: lux_get_url
  when: lux_mktemp|success

- name: Ensure that the lux-release package is installed
  tags: lux
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: lux_yum
  with_items: "{{ lux_mktemp.stdout }}"
  when: lux_get_url|success

- name: Applying lux.repo configurations
  tags: lux
  become: true
  template:
    src: lux.repo.j2
    dest: /etc/yum.repos.d/lux.repo
    owner: root
    group: root
    mode: 0644
  when: lux_yum|success

- name: Ensure that the Lux GPG keys are installed
  tags: lux
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-LUX
    state: present

- name: Purging temporary package from filesystem
  tags: lux
  file:
    path: "{{ lux_mktemp.stdout }}"
    state: absent
  when:
    - lux_mktemp|success
    - lux_yum|success
...
